
[package]
name = "_core"
version = "0.2.2"
edition = "2021"


[dependencies]
neospy_core = { version = "*", path = "src/neospy_core", features=["pyo3"]}
pyo3 = { version =  "0.21", features = ["extension-module"] }
serde = { version = "*", features = ["derive"] }
bincode = {version = "2.0.0-rc.3", features=["derive", "serde"]}
ndarray = "*"
nalgebra = "*"
itertools = "*"
rayon = "*"

[lib]
name = "_core"
path = "src/neospy/rust/lib.rs"
crate-type = ["cdylib"]

[workspace]
members = ["src/neospy_core"]
default-members = ["src/neospy_core"]

[profile.release]
opt-level = 3