# This workflow will install Python dependencies, run tests, lint, and build docs
# This run for every pull request

name: Build Docs

on:
  push:
    branches: [ "main" ]

env:
  NEOSPY_CACHE_DIR: ${{ github.workspace }}/docs/data

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools
    - name: Build neospy
      run: |
        python3 -m pip install '.[dev]' -v
    - name: Build Docs
      run: |
        (cd docs && make clean && make html && make doctest)
    - name: Fix permissions
      run: |
        chmod -c -R +rX "docs/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: "github-pages"
        path:
          docs/html/

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
